tbaApiKey: 98IYKNSHQoj4RonA9UXmDVnvRqRRdLOicOWALLebLNiENK3ZZkmXXB2i5mGEIxx4
tbaComp: 2019wimi
teamnum: 5148
matchScout:
  - type: header
    text: "Autonomous"
  - type: counter
    text: "Balls Auto"
    min: 0
    def: 0
    max: 100
  - type: header
    text: "Teleoperated"
  - type: counter
    text: "Balls Low"
    min: 0
    def: 0
    max: 100
  - type: counter
    text: "Balls High"
    min: 0
    def: 0
    max: 100
  - type: checkbox
    text: "Control Panel"
    def: 0
  - type: checkbox
    text: "Climb"
    def: 0
  - type: checkbox
    text: "Balanced"
    def: 0
  - type: header
    text: "Miscellaneous"
  - type: checkbox
    text: "Robot Issues"
    def: 0
  - type: desc
    text: "Specify anything that impressed you or issues that occured with the robot in the comments below."
graphs:
  - type: scatter
    location: overview
    title: "Test Graph"
    x: 1
    y: 2